config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'

  resources :restaurants, only: [:index, :show] do
    post 'favorites', to: 'restaurants#toggle_favorites'
  end

  resources :favorites, only: [:index]
  resources :answers, only: [:index, :new, :create]
  resources :reviews, only: [:index, :new, :create, :edit, :update]
  resource :profile, only: :show
  resources :coupons, only: :index

  namespace :manager do
    resources :restaurants, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :question_pools, only: [:new, :create, :destroy, :index]
    get 'dashboard', to: 'restaurants#dashboard'
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :owner, class_name: 'User'
  has_many :restaurant_photos
  has_many :reviews
  has_many :coupons
  has_one :question_pools
  has_many :questions, through: :question_pools

  validates :owner, presence: true
  validates :name, presence: true
  validates :siret, presence: true, uniqueness: true
  validates :address, presence: true
  validates :pricing, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..3 }

  # validates :hours, presence: true
  # validates :description, presence: true
  # validates :category, presence: true
  # validates :phone_number, presence: true # regex numéro francais
  # validates :website, presence: true

  private

  def valid_siret?
    # self.siret
    tmp = self.siret.gsub(/\D/, '')
    return false if tmp.length != 14

  end

end

app/controllers/manager/question_pools_controller.rb
class Manager::QuestionPoolsController < ApplicationController

  def new
    @user_id = current_user.id
    @question_pool = QuestionPool.new
    @questions = @question_pool.questions.build
  end

  def create
    if QuestionPool.where(user: current_user).empty?
      @question_pool = QuestionPool.new(question_pool_params)
      @question_pool.user = current_user
      @question_pool.save
      redirect_to new_manager_question_pool_path
    else
      @question_pool = QuestionPool.where(user: current_user)
      @question_pool.update question_pool_params
      redirect_to new_manager_question_pool_path
    end
  end

  def index
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
  end

  private

  def question_pool_params
    params.require(:question_pool).permit(:nameq, questions_attributes: [:name, :id, :cat])
  end
end

app/controllers/manager/questions_controller.rb
class Manager::QuestionsController < ApplicationController

  # def index
  #   @questions = current_user.questions
  # end

  # def new
  #   @question = Question.new
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  # end

  # def create
  #   @question = Question.new(question_params)
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #   @question.restaurant = @restaurant
  #   @question.save!
  # end

  # private

  # def question_params
  #   params.require(:question).permit(:name)
  # end

end

app/controllers/manager/restaurants_controller.rb
class Manager::RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurants, only: [:index, :dashboard]

  def index
    # @restaurants = current_user.restaurants
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner = current_user
    @restaurant.save
    redirect_to manager_restaurant_path(@restaurant)
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to manager_restaurant_path(@restaurant)
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to manager_restaurants_path
  end

  def dashboard
    # @restaurants = current_user.restaurants
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :description, :hours, :pricing, :phone_number, :website)
  end
  
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def set_restaurants
    @restaurants = current_user.restaurants
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_restaurant, only: [:show, :toggle_favorites]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
    @userfavorite = Favorite.where(user: current_user, restaurant: @restaurant).first
    if @userfavorite.nil?
      @toto = false
    else
      @toto = @userfavorite.value
    end
  end

  def toggle_favorites
    @user = current_user
    # @restaurant = Restaurant.find(params[:restaurant_id])
    userfavorite = Favorite.where(user: current_user, restaurant: @restaurant).first
    if userfavorite.nil?
      Favorite.create(user: current_user, restaurant: @restaurant, value: true)
    else
      userfavorite.toggle("value")
      if userfavorite.save
        respond_to do |format|
          format.html { redirect_to restaurant_path(@restaurant) }
          format.js  # <-- will render `app/views/reviews/toggle_favorites.js.erb`
        end
      else
        respond_to do |format|
          format.html { render 'restaurants/show' }
          format.js  # <-- idem
        end
      end
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/views/manager/restaurants/dashboard.html.erb
<div class="main-container">
   <% sorted_group_reviews = Review.all.group("DATE_TRUNC('month', updated_at)") %>
   <div class="dashboard-container">
      <% unless current_user.restaurants.first.nil? %>
      <div id="drag-1" class="draggable">
         <div class="charts-border">
            <div class="draggable-content">
               <p>Répartition des notes</p>
               <% @reviews = current_user.restaurants.first.reviews %>
            </div>
            <div class="charts">
               <% @answer1 = @reviews.where(rating: 1).length %>
               <% @answer2 = @reviews.where(rating: 2).length %>
               <% @answer3 = @reviews.where(rating: 3).length %>
               <% @answer4 = @reviews.where(rating: 4).length %>
               <% @answer5 = @reviews.where(rating: 5).length %>
               <% @data = {
                  labels: ['1', '2', '3', '4', '5'],
                  datasets: [{
                  label: 'note moyenne',
                  # @reviews est une array, la ligne ci dessous recupere la note moyenne (index[1]) contenue pour chaque mois[0..11]
                  data: [@answer1, @answer2, @answer3, @answer4, @answer5],
                  backgroundColor: ['#F0232A', '#F58F21', '#EFEE1A', '#0B9245', '#3951A6'],
                  borderColor:['rgba(143, 214, 148, 0.4)','rgba(255, 255, 148, 0.4)', 'rgba(0, 0, 120, 0.4)', 'rgba(50, 25, 255, 0.4)', 'rgba(50, 255, 255, 0.4)'],
                  fill: false,
                  borderWidth: 1
                  }]
                  } %>
               <% @options = {
                  responsive: true,
                  maintainAspectRatio: false,
                  height: '250px'
               } %>
               <%= doughnut_chart @data, @options %>
            </div>
            <h2 id="average-rating"><%= current_user.restaurants.first.reviews.average(:rating).round(1) %></h2>
         </div>
      </div>
      <div id="drag-2" class="draggable">
         <div class="charts-border">
            <div class="draggable-content">
               <p>Nombre de questionnaires envoyé</p>
            </div>
            <div class="charts">
               <div class="surveys-sent">
                  <% @reviews_sent = current_user.restaurants.first.reviews.count %>
                  <h2><%= @reviews_sent %></h2>
               </div>
            </div>
         </div>
      </div>

      <div id="drag-3" class="draggable">
         <div class="charts-border">
            <div class="draggable-content">
               <p>Taux de réponse</p>
            </div>
            <div class="charts">
              <%#= image_tag "tauxrep.jpg" %>
               <div class="surveys-sent">
                  <% @response_rate = current_user.restaurants.first.reviews.where('created_at != updated_at').count.fdiv(@reviews_sent) * 100 %>
                  <h2><%= @response_rate.round(1) %>%</h2>
               </div>
            </div>
         </div>
      </div>
      <div id="drag-4" class="draggable">
         <div class="charts-border">
            <div class="draggable-content">
               <p>Nombre de réponses par mois</p>
            </div>
            <div class="charts">
               <% @number = sorted_group_reviews.count.sort %>
               <% @number = (0..11).to_a.map{ |i| @number[i].nil? ? [0,0] : @number[i] } %>
               <% @data = {
                  labels: ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin','Juillet','Aout','Septembre','Octobre','Novembre','Decembre'],
                  datasets: [{
                      label: '# de reviews recues',
                      backgroundColor: ['rgba(255, 237, 33, 0.4)','rgba(237, 147, 20, 0.4)', 'rgba(227, 69, 27, 0.4)','rgba(227, 73, 79, 0.4)',
                        'rgba(227, 79, 122, 0.4)','rgba(150, 60, 126, 0.4)','rgba(24, 43, 131,0.4)','rgba(36, 106, 179, 0.4)','rgba(70, 159, 224, 0.4)',
                        'rgba(80, 152, 144, 0.4)','rgba(82, 146, 54, 0.4)','rgba(150, 191, 23, 0.4)'],
                      borderColor:'rgba(143, 214, 148, 0.4)',
                      data: [@number[0][1], @number[1][1], @number[2][1], @number[3][1], @number[4][1], @number[5][1], @number[6][1], @number[7][1], @number[8][1], @number[9][1], @number[10][1], @number[11][1]],
                      borderWidth: 1
                  }]
                  } %>
               <% @options = {
                  legend: { display: false },
                  responsive: true,
                  maintainAspectRatio: false,
                  height: '250px'
               } %>
               <%= bar_chart @data, @options %>
            </div>
         </div>
      </div>
      <div id="drag-5" class="draggable">
         <div class="charts-border">
            <div class="draggable-content">
               <p>Note moyenne par mois</p>
            </div>
            <div class="charts">
               <% @reviews = sorted_group_reviews.average(:rating).sort %>
               <%# Handle case when a month has 0 reviews %>
               <% @reviews = (0..11).to_a.map{ |i| @reviews[i].nil? ? [0,0] : @reviews[i] } %>
                  <% @data = {
                     labels: ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin','Juillet','Aout','Septembre','Octobre','Novembre','Decembre'],
                     datasets: [{
                        label: 'note moyenne',
                        # @reviews est une array, la ligne ci dessous récupère la note moyenne (index[1]) contenue pour chaque mois[0..11]
                        data: [@reviews[0][1]||0, @reviews[1][1]||0, @reviews[2][1]||0, @reviews[3][1]||0, @reviews[4][1]||0, @reviews[5][1]||0, @reviews[6][1]||0, @reviews[7][1]||0, @reviews[8][1]||0, @reviews[9][1]||0, @reviews[10][1]||0, @reviews[11][1]||0],
                        backgroundColor: 'rgba(143, 214, 148, 0.4)',
                        borderColor:'rgba(143, 214, 148, 0.4)',
                        fill: false,
                        borderWidth: 4
                     }]
                     } %>
                  <% @options = {
                     legend: { display: false },
                     responsive: true,
                     maintainAspectRatio: false,
                     height: '250px',
                     # scales: {
                        # yAxes: [{
                        #       ticks: {
                        #       beginAtZero: true
                        #       }
                        # }]
                     # }
                  } %>
                  <%= line_chart @data, @options %>
            </div>
         </div>
      </div>
      <% else %>
        Vous n'avez encore aucune donnée à afficher...
      <% end %>
   </div>
</div>

app/views/manager/restaurants/edit.html.erb
<%= simple_form_for [:manager, @restaurant] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :hours %>
  <%= f.text_field :hours %>
  <%= f.label :pricing %>
  <%= f.text_field :pricing %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.label :website %>
  <%= f.text_field :website %>
  <%= f.submit %>
<% end %>

app/views/manager/restaurants/index.html.erb
<div class="main-container">
      <h1 class="title-page">Mes Restaurants</h1>
      <br>
  <div class="cards-grid mes-restos">
    <% @restaurants.each do |restaurant| %>
    <div class="card-restaurant">
        <img src="https://images.sudouest.fr/2018/02/26/5a940e6b66a4bde56f80a0e1/widescreen/1000x500/le-wrap-a-ete-retire-au-drive-du-mcdo-de-la-sauve.jpg" />
        <div class="card-restaurant-infos">
            <div class="card-restaurant-infos-left">
                <h2><%= restaurant.name %></h2>
                <p class="restaurant-category"><%= restaurant.category %></p>
            </div>
            <div class="card-restaurant-infos-right">
                <p class="restaurant-phone"><%= restaurant.phone_number %></p>
                  <div class="restaurant-rating">
                    <p><%= restaurant.reviews.count %> avis</p>
                  </div>
            </div>
        </div>
    </div>
  <% end %>
  </div>
  <div class="add-btn-resto" style="margin-top: 25px">
    <%= link_to("Ajouter un nouveau restaurant", new_manager_restaurant_path) %>
  </div>
</div>

app/views/manager/restaurants/new.html.erb
<div class="main-container">
  <div class="main-container-bis">
    <h1 class="title-page"> Ajouter un nouveau restaurant</h1>
    <br>
    <div class="form-container">
      <%= simple_form_for [:manager, @restaurant] do |f| %>
        <div class="text-input-form">
          <h4><%= f.label :name, "Nom" %></h4>
        <p><%= f.text_field :name %></p></div>
        <div class="text-input-form">
          <h4><%= f.label :category, "Catégorie" %></h4>
        <p><%= f.text_field :category %></p></div>
        <div class="text-input-form">
          <h4><%= f.label :address, "Adresse" %></h4>
        <p><%= f.text_field :address %></p></div>
        <div class="text-input-form">
          <h4><%= f.label :description, "Description" %></h4>
        <p><%= f.text_field :description %></p></div>
        <div class="text-input-form">
          <h4><%= f.label :hours, "Horaires d'ouverture" %></h4>
        <p><%= f.text_field :hours %></p></div>
        <div class="text-input-form">
          <h4><%= f.label :pricing, "Gamme de prix (€, €€ ou €€€)"%></h4>
        <p><%= f.text_field :pricing %></p></div>
        <div class="text-input-form">
          <h4><%= f.label :phone_number, "Numéro de téléphone" %></h4>
        <p><%= f.text_field :phone_number %></p></div>
        <div class="text-input-form">
          <h4><%= f.label :website, "Site web" %></h4>
        <p><%= f.text_field :website %></p></div>
          <div class="text-input-form">
          <h4><%= f.label :siret, "Numéro Siret" %></h4>
        <p><%= f.text_field :siret %></p></div>
        <div class="add-btn-resto"><%= f.submit %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/manager/restaurants/show.html.erb
<div class="main-container">
      <h1><%= @restaurant.name %></h1>
      <p><%= @restaurant.category %></p>
      <p><%= @restaurant.description %></p>
      <h2><%= link_to("Créer un sondage", new_manager_question_pool_path) %></h2>
      <h2><%= link_to("Réponses du sondage", manager_question_pools_path) %></h2>
      <h2><%= link_to("Editer restaurant", edit_manager_restaurant_path) %></h2>
      <h2><%= link_to "Supprimer restaurant", manager_restaurant_path(@restaurant),
            method: :delete,
            data: { confirm: "Etes-vous sûr?" } %></h2>
      <br>
      <h2><%= link_to("Retour à mes restaurants", manager_restaurants_path) %></h2>
</div>