config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'

  resources :restaurants, only: [:index, :show] do
    post 'favorites', to: 'restaurants#toggle_favorites'
  end

  resources :favorites, only: [:index]
  resources :answers, only: [:index, :new, :create]
  resources :reviews, only: [:index, :new, :create, :edit, :update]
  resource :profile, only: :show
  resources :coupons, only: :index

  namespace :manager do
    resources :restaurants, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :question_pools, only: [:new, :create, :destroy, :index]
    get 'dashboard', to: 'restaurants#dashboard'
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="footer_infos">
        <div class="footer-category">
          <h4 role="presentation"><div>The Honest Meal</div></h4>
            <div class="footer-title">
              <li>Actualités</li>
              <li>Règles</li>
              <li>Aide</li>
            </div>
        </div>


        <div class="footer-category">
          <h4 role="presentation"><div>Decouvrir</div></h4>
            <div class="footer-title">
              <li>Un réseau basé sur la confiance</li>
              <li>Devenir acteur du réseau The Honest Meal</li>
            </div>
        </div>

<!--       <div class="col-3">
        <div class="footer-category">
          <h4 role="presentation"><div>Voyager</div></h4>
            <div class="footer-title">
              <li>Pourquoi utiliser notre application</li>
              <li>Le guide du bon loueur</li>
              <li>Louer responsable</li>
              <li>La communauté</li>
            </div>
        </div>
      </div> -->

        <div class="footer-links">
          <ul class="footer-category">
            <li class="social-logos"><span><a href="https://github.com/Benoit-Baumann/low-boat-homie" target="_blank"><i class="fab fa-sm fa-github"></i></a></span>
            <span><a href="mailto:jgregoire9244@hotmail.fr"><i class="fas fa-sm fa-at"></i></a></span>
            <span><a href="https://trello.com/b/Z1vSWMQl/bienvenue-sur-trello" target="_blank"><i class="fab fa-sm fa-trello"></i></a></span>
            <span><a href="#"><i class="fab fa-sm fa-twitter"></i></a></span>
            <span><a href="#"><i class="fab fa-sm fa-linkedin"></i></a></span></li>
            <li>Conditions</li>
            <li>Plan du site</li>
            <li>Fonctionnement du site</li>
          </ul>
        </div>
  </div>

  <div class="footer-copyright text-center">
  Made with <i class="fas fa-heart"></i> at LeWagon Lyon (Batch 308)
  </div>

</div>

app/views/shared/_login_form.html.erb
<div class="details-container">
  <div class="tab-header-container">
    <div class="tab-header active" id="tab-session">
      <h2>Se connecter</h2>
    </div>
    <div class="tab-header" id="tab-registration">
      <h2>Créer un compte</h2>
    </div>
  </div>

  <div class="tab-container">
    <div class="tab-content active" id="session-form">
      <%= render partial: 'devise/sessions/new' %>
    </div>
    <div class="tab-content" id="registration-form">
      <%= render partial: 'devise/registrations/new' %> 
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar" class="navbar navbar-expand-sm navbar-lewagon">
 <li class="nav-logo" style="list-style: none;">
   <%= link_to root_path, class: "navbar-brand" do %>
     <%= image_tag "theHonestMeal.jpg", class: "logo" %>
   <% end %>
    <p> The Honest Meal </p>
 </li>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <ul class="navbar-nav">
     <% if user_signed_in? %>
         <%= link_to "Dashboard", manager_dashboard_path, class: "connected-btn #{'active' if params[:action] == 'dashboard' and params[:controller] == 'manager/restaurants'}" %>
         <%= link_to "Mon Questionnaire", new_manager_question_pool_path, class: "connected-btn #{'active' if params[:action] == 'new' and params[:controller] == 'manager/question_pools'}" %>
         <%= link_to "Résultats Questionnaire", manager_question_pools_path, class: "connected-btn #{'active' if params[:action] == 'index' and params[:controller] == 'manager/question_pools'}" %>
         <%= link_to "Coupons", coupons_path, class: "connected-btn #{'active' if params[:action] == 'index' and params[:controller] == 'coupons'}" %>
          <details id="share-review-details-form">
            <summary id="share-review-summary" class="connected-btn">Envoyer Questionnaire</summary>
            <%= render partial: 'reviews/share_review_form' %>
          </details>
       <li class="nav-item dropdown">
         <%= image_tag current_user.photo.url(:bright_face), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
         <% if current_user.status == 'customer' %>
           <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
             <%= link_to "Mon profil", profile_path, class: "dropdown-item" %>
             <%= link_to "Mes favoris", favorites_path, class: "dropdown-item" %>
             <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
           </div>
         <% else %>
           <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
             <%= link_to "Mon profil", profile_path, class: "dropdown-item" %>
             <%= link_to "Mes restaurants", manager_restaurants_path, class: "dropdown-item" %>
             <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
           </div>
         <% end %>
       </li>
     <% else %>
      <details>
        <summary class="connected-btn" id="navbar-login-opener">S'identifier</summary>
        <%= render partial: 'shared/login_form' %>
      </details>
     <% end %>
   </ul>
 </div>
</div>

app/views/shared/_restaurant_cards.html.erb
<div class="cards-grid">
    <% restaurants.each do |restaurant| %>
    <% if restaurant.restaurant_photos.first != nil %>
        <% background_url = cl_image_path restaurant.restaurant_photos.first.photo, crop: :fill %>
    <% else %>
        <% background_url = image_path 'restaurant1.jpg' %>
    <% end %>
    <div class="card-restaurant">
        <%= link_to "", restaurant_path(restaurant), class: 'card-link' %>
        <img src="<%= background_url %>" />
        <div class="card-restaurant-infos">
            <div class="card-restaurant-infos-left">
                <h2><%= restaurant.name %></h2>
                <p class="restaurant-category"><%= restaurant.category %></p>
            </div>
            <div class="card-restaurant-infos-right">
                <p class="restaurant-phone">Tél: <%= restaurant.phone_number %></p>
                <div class="restaurant-rating">
                    <p><%= restaurant.reviews.count %> avis</p>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/shared/_searchbar.html.erb
<div class="search-bar-div" style="margin: 0 auto">
   <%= form_tag restaurants_path, class: "", method: :get do |f| %>
       <div class="search-bar">
           <%= text_field_tag :name,
           params[:name],
           class: error ? "search-bar-city invalid-search-bar": "search-bar-city",
           placeholder: "Entrez un restaurant"
           %>
           <p class="invalid-search-message"><%= error %></p>
       </div>
       <div class="search-bar">
           <%= text_field_tag :category,
           params[:category],
           class: error ? "search-bar-city invalid-search-bar": "search-bar-city",
           placeholder: "Entrez une catégorie"
           %>
           <p class="invalid-search-message"><%= error %></p>
       </div>
       <%= button_tag(type: "submit", class: "search-bar-button") do %>
           <p>Search</p>
       <% end %>
   <% end %>
</div>