config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'

  resources :restaurants, only: [:index, :show] do
    post 'favorites', to: 'restaurants#toggle_favorites'
  end

  resources :favorites, only: [:index]
  resources :answers, only: [:index, :new, :create]
  resources :reviews, only: [:index, :new, :create, :edit, :update]
  resource :profile, only: :show
  resources :coupons, only: :index

  namespace :manager do
    resources :restaurants, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :question_pools, only: [:new, :create, :destroy, :index]
    get 'dashboard', to: 'restaurants#dashboard'
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :owner, class_name: 'User'
  has_many :restaurant_photos
  has_many :reviews
  has_many :coupons
  has_one :question_pools
  has_many :questions, through: :question_pools

  validates :owner, presence: true
  validates :name, presence: true
  validates :siret, presence: true, uniqueness: true
  validates :address, presence: true
  validates :pricing, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..3 }

  # validates :hours, presence: true
  # validates :description, presence: true
  # validates :category, presence: true
  # validates :phone_number, presence: true # regex numéro francais
  # validates :website, presence: true

  private

  def valid_siret?
    # self.siret
    tmp = self.siret.gsub(/\D/, '')
    return false if tmp.length != 14

  end

end

app/controllers/manager/restaurants_controller.rb
class Manager::RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurants, only: [:index, :dashboard]

  def index
    # @restaurants = current_user.restaurants
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner = current_user
    @restaurant.save
    redirect_to manager_restaurant_path(@restaurant)
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to manager_restaurant_path(@restaurant)
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to manager_restaurants_path
  end

  def dashboard
    # @restaurants = current_user.restaurants
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :description, :hours, :pricing, :phone_number, :website)
  end
  
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def set_restaurants
    @restaurants = current_user.restaurants
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_restaurant, only: [:show, :toggle_favorites]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
    @userfavorite = Favorite.where(user: current_user, restaurant: @restaurant).first
    if @userfavorite.nil?
      @toto = false
    else
      @toto = @userfavorite.value
    end
  end

  def toggle_favorites
    @user = current_user
    # @restaurant = Restaurant.find(params[:restaurant_id])
    userfavorite = Favorite.where(user: current_user, restaurant: @restaurant).first
    if userfavorite.nil?
      Favorite.create(user: current_user, restaurant: @restaurant, value: true)
    else
      userfavorite.toggle("value")
      if userfavorite.save
        respond_to do |format|
          format.html { redirect_to restaurant_path(@restaurant) }
          format.js  # <-- will render `app/views/reviews/toggle_favorites.js.erb`
        end
      else
        respond_to do |format|
          format.html { render 'restaurants/show' }
          format.js  # <-- idem
        end
      end
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/views/restaurants/index.html.erb
<div class="main-container">
  <h1>Restaurants près de XXX</h1>
  <br>
  <div class="restaurant-grid">
    <%= render partial: 'shared/restaurant_cards', locals: {restaurants: @restaurants} %>
  </div>
</div>

app/views/restaurants/show.html.erb
<% if @toto %>
<h1>Restaurant</h1>
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.description %></p>
<%= link_to restaurant_favorites_path(@restaurant), method: :post, :remote => true do %>
  <i class="fas fa-heart valueoff"></i>
<% end %>
<% else %>
<h1>Restaurant</h1>
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.description %></p>
<%= link_to restaurant_favorites_path(@restaurant), method: :post, :remote => true do %>
  <i class="fas fa-heart valueon"></i>
<% end %>
<% end %>

app/views/restaurants/toggle_favorites.js.erb
if (document.querySelector(".fa-heart").className == "fas fa-heart valueoff") {
  document.querySelector(".fa-heart").classList.remove("valueoff");
  document.querySelector(".fa-heart").classList.add("valueon");
} else {
  document.querySelector(".fa-heart").classList.remove("valueon");
  document.querySelector(".fa-heart").classList.add("valueoff");
}