config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'

  resources :restaurants, only: [:index, :show] do
    post 'favorites', to: 'restaurants#toggle_favorites'
  end

  resources :favorites, only: [:index]
  resources :answers, only: [:index, :new, :create]
  resources :reviews, only: [:index, :new, :create, :edit, :update]
  resource :profile, only: :show
  resources :coupons, only: :index

  namespace :manager do
    resources :restaurants, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :question_pools, only: [:new, :create, :destroy, :index]
    get 'dashboard', to: 'restaurants#dashboard'
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:edit, :update]

  def index
    @reviews = current_user.reviews
  end

  def new
  end

  def create
    @email = params[:email]
    unless valid_email(@email)
      render :invalid_email
      return

    end
    @restaurant = Restaurant.find(params[:restaurant])
    @review = Review.new(restaurant: @restaurant)
    if @review.save
      ReviewMailer.with(review: @review, email: @email).send_link.deliver_now
    else
      render :invalid_email
    end
  end

  def edit
    @answer = Answer.new
    @review = Review.find_by(token: params[:id])
    if @review.nil?
      render :invalid_review
    elsif @review.updated_at > @review.created_at
      render :burnt_review
    elsif (Time.now - @review.created_at.to_time)/1.day > 7
      render :expired_review, locals: { review: @review }
    end
  end

  def update
    @review = Review.find_by(token: review_params[:token])
    username = review_params[:username].nil? ? '' : review_params[:username]
    if review_params[:username].nil?
      @review.user = current_user
      @username = current_user.username
    else
      @review.username = review_params[:username]
      @username = review_params[:username]
    end
    if @review.update(content_title: review_params[:content_title],
                      content: review_params[:content],
                      rating: review_params[:rating])
      @coupon = Coupon.new(restaurant: @review.restaurant,
        details: ['Un café gratuit au choix', 'Un dessert maison gratuit', "Une boisson fraîche gratuite"].sample,
        username: @username).save!
      render :validated_review
    else
      render :edit, locals: { review: @review }
    end

    answer_params[:answers].each do |answer|
      Answer.new(content: answer[:content], question_id: answer[:question_id]).save
    end
  end

  private

  def review_params
    params.require(:review).permit(:user, :restaurant, :username, :content_title, :content, :rating, :token, :email)
  end

  def answer_params
    params.require(:review).permit(answers: [:question_id, :content])
  end

  def valid_email(email)
    check = email =~ URI::MailTo::EMAIL_REGEXP
    return check == 0
  end

end

app/views/reviews/_share_review_form.html.erb
<div class="details-container share-review">

  <h2 class="title-page">Envoyer le questionnaire</h2>

  <%= form_tag reviews_path, class: "", method: :post, remote: true do |f| %>
      <div class="share-review-form-container">
          <%= select_tag :restaurant, options_from_collection_for_select(current_user.restaurants, "id", "name") %>
          <%= text_field_tag :email, nil, placeholder: "John.doe@example.com" %>
          <%= button_tag(type: "submit", class: "publier-questionnaire") do %>
            <p class="link-text">Envoyer</p>
          <% end %>
          <p class="feedback-msg"></p>
      </div>
  <% end %>

</div>

app/views/reviews/burnt_review.html.erb
<h1>Humm... Il semblerait bien que ce lien ai deja été utilisé pour laisser un commentaire...</h1>
<!-- Mettre un icone qui fait un clin d'oeil avec une phrase du genre "1 lien = 1 review et 1 lien / 2 reviews = Impossible" -->

app/views/reviews/create.js.erb
console.log('Review sent!');
msg = document.querySelector('.feedback-msg');
msg.innerHTML = "Email envoyé !"
msg.className = "feedback-msg success";

app/views/reviews/edit.html.erb
<div class="restaurant-summary">
  <div class="restaurant-photo">
    <%= image_tag "lebouchonduwagon.jpg"%>
  </div>
  <div class="restaurant-info">
    <h2><%= @review.restaurant.name %></h2>
    <p><%= @review.restaurant.address %></p>
  </div>
</div>

<div class="main-container">
  <div class="review2">

    <div class="review-title2">
      <h2>Laissez un avis concernant le restaurant <span class='italic-green-text'><%= @review.restaurant.name %></span></h2>
    </div>


    <%= simple_form_for [@review], html: { class: "form-review"} do |f| %>
      <div class="input-boxes-review">
        <div class="review-title2">
          <h3>Commentaire</h3>
        </div>
        <%= f.input :token, as: :hidden, input_html: { value: @review.token } %>
        <%= f.input :username, label: "Nom d'utilisateur", :input_html => { class: "input-type input-space" }, required: true unless user_signed_in? %>
        <%= f.input :content_title, label: 'Titre de votre avis', :input_html => { class: "input-type input-space" } %>
        <%= f.input :content, label: 'Votre avis', :input_html => { class: "input-type input-space" } %>
        <%= f.input :rating, collection: (1..5).to_a, label: 'Votre note', :input_html => { class: "input-type input-space" } %>

        <br>
        <br>
        <br>
        <br>
        <% unless @review.restaurant.owner.question_pools.empty? %>
          <div class="review-title3">
            <h3>Donnez-nous votre avis sur les points suivants</h3>
          </div>
          <p class='disclaimer'>Les questions ci-dessous sont uniquement destinées au restaurateur et ne seront pas rendues publiques</p>
          <% QuestionPool.find_by(user_id: @review.restaurant.owner.id).questions.each do |question| %>
              <%= f.fields_for 'answers[]', Answer.new(question: question) do |a| %>
                <% if question.cat == '0' %>
                  <%= a.input :question_id, as: :hidden %>
                  <%= a.input :content, label: question.name, :input_html => { class: "input-type input-space" } %>
                <% else %>
                  <%= a.input :question_id, as: :hidden %>
                  <%= a.input :content, collection: (1..5).to_a, label: question.name, :input_html => { class: "input-type starquestion input-space" } %>
                <% end %>
              <% end %>
          <% end %>
        <% end %>

      <div class="form-actions submit">
        <%= f.submit "Publier", class: "join-us-btn btn-padding" %>
      </div>

      </div>
    <% end %>

  </div>
</div>

app/views/reviews/expired_review.html.erb
<h1>Ce lien a malheureusement expiré...</h1>
<i class="fas fa-check-circle"></i>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<% @reviews.each do |review| %>
    <%= review.content %>
<% end %>

app/views/reviews/invalid_email.js.erb
console.log('Invalid email !');
emailInput = document.querySelector('#email');
emailInput.focus();
msg = document.querySelector('.feedback-msg');
msg.innerHTML = "Adresse email invalide !";
msg.className = "feedback-msg fail";

app/views/reviews/invalid_review.html.erb
<div class="error">
  <li style="list-style: none">
    <h1>Humm... Ce lien ne semble pas être valide...</h1>
    <img src="/images/torch.png" alt="">
    <i class="fas fa-check-circle fa-2x"></i>
    <i class="fas fa-exclamation-triangle fa-2x"></i>
  </li>
</div>

app/views/reviews/review_expired.html.erb
<h1>Unfortunately, the link you received to leave a review for <%= @review.restaurant.name %> has expired...</h1>

app/views/reviews/validated_review.html.erb
<div class="main-container">
  <header class="site-header" id="header">
    <h1 class="title-page-thank-you" style="border-top: none;">MERCI !</h1>
  </header>

  <div class="main-content">
    <div class="Checked-Green"><i class="fa fa-check main-content__checkmark" id="checkmark"></i></div>
    <div class="main-page-thank-you"><p>Vous recevrez d'ici peu un email contenant le coupon promotionnel utilisable dans le restaurant !</p></div>
  </div>
</div>